version: '2'

services:
  website:
    build: ./website/
    image: morphic-website
    ports:
      - 8080:8080
  backend:
    build: ./backend/
    image: morphic-backend
    ports:
      - 5000:5000
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://morphic:morphic@db:5432/morphic
    volumes:
      - ./backend/:/usr/src/app
  db:
    image: postgres:9.6
    volumes:
      - ./.docker-data/postgres/:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=morphic
     - POSTGRES_USER=morphic
     - POSTGRES_PASSWORD=morphic
